# Generated by Django 5.0.6 on 2024-05-13 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Catalago', '0001_initial'),
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carreto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_lista_productos', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estat', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=7)),
                ('comprar', models.BooleanField(default=False)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente')),
            ],
            options={
                'db_table': 'Carreto',
            },
        ),
        migrations.CreateModel(
            name='ListaProductos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unitats', models.IntegerField()),
                ('id_carreto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarroCompra.carreto')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Catalago.producto')),
            ],
            options={
                'db_table': 'ListaProductos',
            },
        ),
    ]
