# Generated by Django 5.0.6 on 2024-05-14 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarroCompra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carreto',
            name='id_lista_productos',
        ),
    ]
