# Generated by Django 5.0.6 on 2024-05-16 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarroCompra', '0002_remove_carreto_id_lista_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carreto',
            name='comprar',
        ),
    ]
