# Generated by Django 5.0.6 on 2024-05-14 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('import_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField()),
                ('num_tarj', models.CharField(max_length=16)),
                ('data_caducitat_tarj', models.DateField()),
                ('cvc_tarj', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedidos.comanda')),
            ],
            options={
                'db_table': 'Pagos',
            },
        ),
    ]
